services:

  fycsso_database:
    container_name: fycsso_database
    image: mariadb:10.5.12
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fycsso_db
      MYSQL_USER: fycsso_user
      MYSQL_PASSWORD: fycsso_password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql


  fycsso_pma:
    container_name: fycsso_pma
    image: phpmyadmin:latest
    environment:
      PMA_HOST: fycsso_database
    ports:
      - "8080:80"
    depends_on:
      - fycsso_database

  fycsso_nginx:
    container_name: fycsso_nginx
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql:
    driver: local